name: Windows - Anydesk RDP

on:
  workflow_dispatch:

jobs:
  build:
    name: Built Connection to KSP_TECH
    runs-on: windows-latest
    timeout-minutes: 9999
    
    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/khalid-ofcl/rdp-files/main/ksp_tech_rdp.bat" -OutFile "ksp_tech_rdp.bat"
          cmd /c ksp_tech_rdp.bat
          
      - name: Enable TS
      - name: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
      - name: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
      - name: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

      - name: Log In To AnyDesk
        run: cmd /c start_rdp.bat

      - name: Time Counter
        run: Start-Sleep -Seconds 21600
